[package]
name = "sensador"
version = "0.1.0"
authors = ["Kilian Gärtner <kilian.gaertner@naymspace.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille= "3.0.0"
